apiVersion: v1
kind: Service
metadata:
  labels:
    app: mealie
  name: mealie
  namespace: devops
spec:
  ports:
  - port: 8000
    protocol: TCP
    targetPort: 9000
  selector:
    app: mealie
  type: LoadBalancer
