apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mealie-data
  namespace: devops
  labels:
    app: mealie-data
    
spec:
  storageClassName: local-path
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi