apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: devops
spec:
  containers:
  - image: nginx:1.14.2
    name: test-container
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - mountPath: /cache
      name: cache-volume
  - image: busybox
    name: test-container-2
    ports:
      - containerPort: 8080
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
      - mountPath: /cache
        name: cache-volume

  volumes:
  - name: cache-volume
    emptyDir:
      sizeLimit: 500Mi
